### PR TITLE
Very simple routine to detach a binary on-the-fly

### PR DESCRIPTION
**Pull request by mathren**
The routine `detach_binary` can be used to transform a binary run with `evolve_both_stars = .true.` into a run where only the secondary star is evolved: it turns star 1 into a point mass, turns off orbital evolution, and sets an infinite separation.

It can be used to focus on models of secondary stars without having to deal with the very late core burning phases of the donor and can be used to simulate, for example, massive binaries that are disrupted at the core collapse of the donor star.

When trying to use `mesa_error` to interrupt the run in case the secondary star is a point mass, I am somehow running into 
```Error: Syntax error in argument list at (1)```
so I've instead opted for a `stop` with an informative statement.

I have tested this successfully with mesa 15140 and with the main branch of MESA (commit hash in the readme).

### CODE REVIEW

**Comment by mathren** [comment]
That is correct! I've edited the README according to your feedback. 

Re: `mesa_error`, it might be an issue with the length of my environment variables `$MESA_CONTRIB_DIR` and `$MESA_DIR`, but on two different machines I get:

```
Error: Syntax error in argument list at (1)
make: *** [$MESA_DIR/binary/work_standard_makefile_binary:56: run_binary_extras.o] Error 1
```

**Comment by warrickball** [comment]
The `mesa_error` problem appears to be because the `__FILE__` and `__LINE__` preprocessor macros aren't processed when they're in `include`d files. The macros appear to expand to nothing, causing the compilation failure.

One workaround is to not try to handle the error in the included subroutine but rather return the non-zero `ierr` to the call in `run_star_extras.f90` and then call `mesa_error` there. That's what I do in `hydro_Ttau/astero_example`.

I'm happy to merge after you make that change, unless you object to making it, in which case I don't mind merging anyway even if it isn't MESA style. I admit that stopping in the included file defends against users who don't check `ierr` after the call.

**Comment by mathren** [comment]
Thanks for the explanation! As a user, I think it is safest to leave the `STOP` with the string. Nevertheless, I have added `ierr=1` before the `STOP` and tried to guide interested users to the right workaround in the comments and README.

**Comment by mathren** [comment]
Might be worth updating the instructions at: https://docs.mesastar.org/en/latest/developing/code_style.html#stop with this piece of info though.

**Comment by warrickball** [comment]
> Might be worth updating the instructions at: https://docs.mesastar.org/en/latest/developing/code_style.html#stop with this piece of info though.

Agreed!

**Pull request merged**
