### PR TITLE
Implementation of the Fuller et al. angular momentum transport

### PR DESCRIPTION
**Pull request by mathren**
There are two versions, from Fuller et al. 2019 and Fuller & Lu 2022,
respectively.

In both cases, the functions have been taken from the zenodo repositories
associated to these papers (all linked in the README here) and adapted for
the current MESA version (r24.03.1). Specifically this means:

* removing `_cr` from the math functions (since cr_lib is not part of MESA anymore)
* propagating the star `id` from the TSF* function to diffmag and ultimately `sige2`
* adding a `s%` pointer in `sige2`, intialize it with `id` above
  to obtain `s% kap_handle` to obtain the electron conduction opacity

The rest of the code is left untouched (including their comments) to have
a bug-for-bug reproduction of the original work of Jim Fuller and collaborators.

The example folder just calls the function corresponding to the Fuller & Lu 2022
implementation and is kept very minimal.

This is intended to make it easy to test this angular momentum prescriptions.

### CODE REVIEW

**Comment by mathren** [comment]
Note that I emailed Jim Fuller before this PR to get his approval

**Comment by warrickball** [comment]
Hi @mathren, and thanks for this contribution! I'll start with a few things that are blockers for me:

1. `TSF_Fuller_Lu22` doesn't seem to do anything near the inner and outer boundaries, the way `TSF_Fuller19` does. That is, `TSF_Fuller19` loops over `k=nsmooth+1,s% nz-(nsmooth+1)`, then `k=s% nz-nsmooth,s% nz` and then `k=nsmooth,1`, whereas `TSF_Fuller_Lu22` only does the first of these three. Is that intentional?
2. Could you set up the example to be something that exercises the AM transport prescription? Maybe something that reproduces a curve from Fuller et al. (2019) or Fuller & Lu (2022). As it is it doesn't look like the model is even rotating. I like to think of these as something like test suite cases and I hope to automatically test them one day. It'd help make sure nothing gets broken by trying to improve the code in small ways (e.g. using `pi` from `math_lib`). (This is something I should document here better.)

There are some other minor things that I don't mind changing myself later. I.e, these won't prevent me from merging.

1. It'd be nice to adhere better to the MESA [coding style](https://docs.mesastar.org/en/release-r24.03.1/developing/code_style.html).
2. The example should be named `star_example` to be picked up by the `check_examples.sh` script that tries building all the examples. (I think I also need to document this better.)
3. The code could do with refactoring. The way I'd do this is by defining functions something like

```f90
subroutine TSF_Fuller19_or_FullerLu22(Lu22, id, ierr)
   logical, intent(in) :: Lu22
   integer, intent(in) :: id
   integer, intent(out) :: ierr

   ...
end subroutine TSF_Fuller19_or_FullerLu22

subroutine TSF_Fuller19(id, ierr)
    ...
   call TSF_Fuller19_or_FullerLu22(.false., id, ierr)
end subroutine TSF_Fuller19

subroutine TSF_FullerLu22(id, ierr)
    ...
   call TSF_Fuller19_or_FullerLu22(.true., id, ierr)
end subroutine TSF_FullerLu22
```
I.e. define the current functions in terms of a single function that only needs a few logical blocks (e.g. for the default parameters) to distinguish between the two cases. As it is the two versions have unexpected though largely cosmetic differences in implementation (e.g. `**` vs `pow`). This is just one suggestion though; you might devise a more sensible way of doing it.

**Comment by warrickball** [comment]
> * adding a s% pointer in sige2, intialize it with id above to obtain s% kap_handle to obtain the electron conduction opacity

I'm thinking about this and I think I prefer getting the electron conduction opacity _outside_ of `diffmag` and passing it as a parameter. Coupling `diffmag` to the star pointer by passing `id` around seems like unnecessary coupling. `diffmag` doesn't need to know about the whole star. (This is also something I'm prepared to fix later and won't stop me merging.)

**Comment by mathren** [comment]
Hi Warrick! Thanks for your feedback.

1. that is how Fuller et al. implemented things in the routines published on zenodo, I really tried to minimized how much I changed things. You raise a valid point, but I don't know the answer here, we would need Jim to chime in. I can email him (and cc you)
2. yes, I can setup rotation in this example (was a mistake not to do it, I've tested in a more complex setup with rotation that things do work). Not sure if I can reproduce their results with the new MESA version directly though.

Similarly, for the many minor things you mention, my aim here was to touch as little as possible the routines taken from the zenodo repositories associated with their papers. I just copy-pasted them, compiled, and fixed the errors that the compile threw one by one until it worked. I didn't want to risk introducing mistakes in work that is not mine to begin with.

**Comment by warrickball** [comment]
Thanks for the quick reply. The absence of the extra loops in `TSF_Fuller_Lu22` is the only thing that looks like a bug. With an example that makes use of the prescription, I can experiment with the cosmetic stuff and diff the output as necessary to make sure I don't change anything later but, as I said, I won't let it hold up merging.

**Comment by mathren** [comment]
I've pushed a better example folder (including a rotating star) that compiles and runs. That is obviously not meant to be for scientific quality results, but, in the spirit of the test cases, just to test that the routines can be successfully called.

I've also pinged Jim regarding the issue at point 1. Quoting directly:

>  it was intentional to cut out the extra loops around the boundaries. I think it was just an effort to make the code simpler. I don't recall ever seeing any problems associated with the boundaries, but I suppose it's possible this could occur in some situations. I only wrote the routine to be good enough to be reliable for the stellar models I was running at the time. As is common with MESA, there could certainly be other situations that cause problems, and we'll probably run into those if more people try to use these prescriptions!

So I guess we need to make a decision: fidelity to the implementation of Fuller & Lu 2022 without the boundary loop or changing it? My personal inclination is towards remaining as close as possible to the published results (so there is something that one can refer to) unless one encounters issues.

**Comment by warrickball** [comment]
> My personal inclination is towards remaining as close as possible to the published results (so there is something that one can refer to) unless one encounters issues.

Yes, I agree. I'll take the new example out for a spin (pun intended) probably this evening and, presuming that all looks good, merge this.

**Comment by warrickball** [comment]
I've just had a go at refactoring some of this code and noticed that the Fuller et al. (2019) formulation uses $C_V$ in the thermal diffusivity,

https://github.com/MESAHub/mesa-contrib/blob/1666ebab5fbb8ec3ea185e2391b6fcf0e56148a4/hooks/Fuller_AM/Fuller_AM_transport.inc#L32

whereas the Fuller & Lu (2022) formulation uses $C_P$:

https://github.com/MESAHub/mesa-contrib/blob/1666ebab5fbb8ec3ea185e2391b6fcf0e56148a4/hooks/Fuller_AM/Fuller_AM_transport.inc#L199

Do you happen to know if this is intentional? I note that MESA itself uses $C_P$. [E.g.,](https://github.com/MESAHub/mesa/blob/27b932d2d2ec6d237870803c1f2bb11bdd9ec787/star/private/rotation_mix_info.f90#L1188-L1189)
```f90
            xkap = 16d0*boltz_sigma*T(k)*T(k)*T(k)/ &
               (3d0*opacity(k)*rho(k)*rho(k)*Cp(k)) ! thermal diffusivity
```
I'm not an expert on these coefficients and a short dig in the paper didn't define them. I'm happy to ask Jim myself, if you don't happen to know.

**Comment by mathren** [comment]
I don't know from the top of my head indeed...best to ask Jim

**Pull request merged**
